ur5_manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
ur10_manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver: dual_arm_robot_ur10_manipulator_kinematics/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
